[versions]
accompanist = "0.37.3"
androidGradlePlugin = "8.13.0"
androidxActivity = "1.11.0"
androidxAppCompat = "1.7.1"
androidxMaterial = "1.13.0"
androidxComposeBom = "2025.10.01"
androidxComposeRuntimeTracing = "1.9.4"
material3 = "1.4.0"
androidxCore = "1.17.0"
androidxDataStore = "1.1.7"
androidxEspresso = "3.7.0"
androidxLifecycle = "2.9.4"
androidxMacroBenchmark = "1.4.1"
benchmark = "1.4.1"
androidxMetrics = "1.0.0"
androidxNavigation = "2.9.5"
androidxProfileinstaller = "1.4.1"
androidxSplashScreen = "1.0.1"
androidxStartup = "1.2.0"
androidxTestArchCore = "2.2.0"
androidxTestCore = "1.7.0"
androidxTestExt = "1.3.0"
androidxTestRules = "1.7.0"
androidxTestRunner = "1.7.0"
androidxTracing = "1.3.0"
androidxUiAutomator = "2.3.0"
androidxWindowManager = "1.5.0"
androidxWork = "2.11.0"
firebaseBom = "34.5.0"
firebaseCrashlyticsPlugin = "3.0.6"
firebasePerfPlugin = "2.0.2"
firebaseDistribution = "5.2.0"
googleOss = "17.3.0"
review = "2.0.2"
googleOssPlugin = "0.10.9"
spotless = "8.0.0"
jacoco = "0.8.14"
junit4 = "4.13.2"
kotlin = "2.2.20"
kotlinxCoroutines = "1.10.2"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJson = "1.9.0"
ksp = "2.2.20-2.0.4"
lint = "31.13.0"
okhttp = "5.3.0"
retrofit = "3.0.0"
retrofitKotlinxSerializationJson = "1.0.0"
robolectric = "4.16"
room = "2.8.3"
secrets = "2.0.1"
turbine = "1.2.1"
ossLicense = "0.10.9"
mpcharts = "v3.1.0"
mockito = "6.1.0"
jxl = "2.6.12"
truth = "1.4.5"
vico = "1.11.1"
play-publish = "3.12.1"
google-services = "4.4.4"
backup-restore = "1.1.0"
gson = "2.13.2"
dependency-analysis = "3.4.1"
lottieCompose = "6.7.0"
opencsv = "5.12.0"
coil = "2.7.0"
koin-bom = "4.1.1"
naveenapps-designsystem = "1.0.7"
naveenapps-settings = "1.0.4"
runtimeAnnotation = "1.10.3"

[libraries]
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidxMaterial" }
androidx-benchmark-macro = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidxMacroBenchmark" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-activity = { group = "androidx.activity", name = "activity-compose" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "material3"  }
androidx-compose-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3"  }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-compose-runtime-tracing = { group = "androidx.compose.runtime", name = "runtime-tracing", version.ref = "androidxComposeRuntimeTracing" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-compose-runtime-annotation = { group = "androidx.compose.runtime", name = "runtime-annotation", version.ref = "runtimeAnnotation" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-dataStore-core = { group = "androidx.datastore", name = "datastore", version.ref = "androidxDataStore" }
androidx-dataStore-preference = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDataStore" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-metrics = { group = "androidx.metrics", name = "metrics-performance", version.ref = "androidxMetrics" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "androidxProfileinstaller" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidxStartup" }
androidx-splash-screen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxSplashScreen" }
androidx-test-core-arch = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidxTestArchCore" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidxUiAutomator" }
androidx-tracing-ktx = { group = "androidx.tracing", name = "tracing-ktx", version.ref = "androidxTracing" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidxNavigation" }
androidx-window-manager = { module = "androidx.window:window", version.ref = "androidxWindowManager" }
androidx-work-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWork" }
androidx-work-testing = { group = "androidx.work", name = "work-testing", version.ref = "androidxWork" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-config = { group = "com.google.firebase", name = "firebase-config" }
firebase-cloud-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf" }
google-android-play-review = { group = "com.google.android.play", name = "review-ktx", version.ref = "review" }
google-oss-licenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "googleOss" }
google-oss-licenses-plugin = { group = "com.google.android.gms", name = "oss-licenses-plugin", version.ref = "googleOssPlugin" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
org-jacoco-core = { module = "org.jacoco:org.jacoco.core", version.ref = "jacoco" }
spotless = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
lint-api = { group = "com.android.tools.lint", name = "lint-api", version.ref = "lint" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
opencsv = { module = "com.opencsv:opencsv", version.ref = "opencsv" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlin-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinxSerializationJson" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
robolectric-shadows = { group = "org.robolectric", name = "shadows-framework", version.ref = "robolectric" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
mpcharts = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpcharts" }
mockito = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito" }
jxl = { group = "net.sourceforge.jexcelapi", name = "jxl", version.ref = "jxl" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
vico-compose = { group = "com.patrykandpatrick.vico", name = "compose", version.ref = "vico" }
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }
vico-core = { group = "com.patrykandpatrick.vico", name = "core", version.ref = "vico" }
backup-restore = { group = "de.raphaelebner", name = "roomdatabasebackup", version.ref = "backup-restore" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-android-work-manager = { module = "io.insert-koin:koin-androidx-workmanager" }
koin-android-compose = { module = "io.insert-koin:koin-androidx-compose" }

naveenapps-designsystem = { module = "com.naveenapps:designsystem", version.ref = "naveenapps-designsystem" }
naveenapps-settings = { module = "com.naveenapps:settings", version.ref = "naveenapps-settings" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsPlugin" }
firebase-performance-gradlePlugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "firebasePerfPlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
app-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version = "2.1.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerfPlugin" }
firebase-distribution = { id = "com.google.firebase.appdistribution", version.ref = "firebaseDistribution" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
oss-license = { id = "com.google.android.gms.oss-licenses-plugin", version.ref = "ossLicense" }
benchmark = { id = "androidx.benchmark", version.ref = "benchmark" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
play-publish = { id = "com.github.triplet.play", version.ref = "play-publish" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis" }

naveenapps-kotlin-basic = { id = "naveenapps.plugin.kotlin.basic", version = "unspecified" }
naveenapps-android-application = { id = "naveenapps.plugin.android.app", version = "unspecified" }
naveenapps-android-application-compose = { id = "naveenapps.android.application.compose", version = "unspecified" }
naveenapps-android-application-firebase = { id = "naveenapps.android.application.firebase", version = "unspecified" }
naveenapps-android-application-flavors = { id = "naveenapps.android.application.flavors", version = "unspecified" }
naveenapps-android-application-jacoco = { id = "naveenapps.android.application.jacoco", version = "unspecified" }
naveenapps-android-feature = { id = "naveenapps.android.feature", version = "unspecified" }
naveenapps-android-library = { id = "naveenapps.android.library", version = "unspecified" }
naveenapps-android-library-compose = { id = "naveenapps.android.library.compose", version = "unspecified" }
naveenapps-android-library-jacoco = { id = "naveenapps.android.library.jacoco", version = "unspecified" }
naveenapps-android-lint = { id = "naveenapps.android.lint", version = "unspecified" }
naveenapps-android-room = { id = "naveenapps.android.room", version = "unspecified" }
naveenapps-android-test = { id = "naveenapps.android.test", version = "unspecified" }
naveenapps-di = { id = "naveenapps.di", version = "unspecified" }
naveenapps-jvm-library = { id = "naveenapps.jvm.library", version = "unspecified" }
